version: '3.8'

services:

  web:
    container_name: 'mysite01'
    image: 'sreelalrp/mysite'
    ports:
     - "80:80"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
